# Generated by Django 2.0.5 on 2018-06-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'communication'), ('model', 'callentity')), models.Q(('app_label', 'communication'), ('model', 'chatentity')), models.Q(('app_label', 'timetables'), ('model', 'visit')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
