# Generated by Django 2.0.6 on 2018-06-07 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0003_auto_20180607_2013'),
        ('payments', '0002_auto_20180606_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Patient'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('object_id', 'content_type')},
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
