# Generated by Django 2.0.2 on 2018-05-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='day of the shift')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='name of the shift')),
                ('start', models.TimeField(verbose_name='start of the shift')),
                ('end', models.TimeField(verbose_name='end of the shift')),
                ('gap', models.DurationField(blank=True, help_text='time in minutes', null=True, verbose_name='time of a visit')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor', verbose_name='doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(verbose_name='start of the visit')),
                ('end', models.TimeField(verbose_name='end of the visit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.Shift')),
            ],
            options={
                'ordering': ['shift', 'start'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.ShiftType', verbose_name='shift_type'),
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('start', 'end', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='shifttype',
            unique_together={('doctor', 'start', 'end')},
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('shift_type', 'day')},
        ),
    ]
