# Generated by Django 2.0.5 on 2018-06-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180607_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='skype',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='skype username'),
        ),
    ]
