# Generated by Django 2.0.5 on 2018-06-12 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180610_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedoctor',
            name='hour_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='hour rate'),
        ),
        migrations.AlterField(
            model_name='privatedoctor',
            name='visit_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='visit price'),
        ),
    ]
