# Generated by Django 2.0.6 on 2018-06-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20180607_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.PositiveIntegerField(blank=True, verbose_name='sum to pay'),
        ),
    ]
