# Generated by Django 2.0.5 on 2018-06-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callentity',
            name='room',
            field=models.CharField(max_length=256, null=True, verbose_name='room name'),
        ),
    ]
