# Generated by Django 2.0.5 on 2018-05-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deceases', '0002_auto_20180526_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceaseagegapgender',
            name='age_gap',
        ),
        migrations.RemoveField(
            model_name='deceaseagegapgender',
            name='decease',
        ),
        migrations.RemoveField(
            model_name='deceaseagegapgender',
            name='gender',
        ),
        migrations.AddField(
            model_name='decease',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='number of people in average to get decease from 10^6'),
        ),
        migrations.DeleteModel(
            name='DeceaseAgeGapGender',
        ),
    ]
