# Generated by Django 2.0.5 on 2018-06-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deceases', '0003_auto_20180527_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decease',
            name='occurrence',
        ),
        migrations.RemoveField(
            model_name='deceasesymptom',
            name='occurrence',
        ),
    ]
