# Generated by Django 2.0.2 on 2018-05-26 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Doctor', verbose_name='doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Patient', verbose_name='patient')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ChatEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hours', models.FloatField(verbose_name='sum of minutes spent on chat')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Doctor', verbose_name='doctor')),
            ],
            options={
                'ordering': ['timestamp'],
                'get_latest_by': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='timestamp')),
                ('doctor_read', models.BooleanField(default=False)),
                ('patient_read', models.BooleanField(default=False)),
                ('text', models.TextField(verbose_name='text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Chat')),
            ],
            options={
                'ordering': ['chat', 'timestamp'],
                'get_latest_by': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chatentity',
            name='messages',
            field=models.ManyToManyField(to='communication.Message'),
        ),
        migrations.AddField(
            model_name='chatentity',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Patient', verbose_name='patient'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('patient', 'doctor')},
        ),
    ]
